import type { NextPage } from 'next'
import Head from 'next/head'
import { Input } from '../components/Input'
import { LinkPreview } from '../components/LinkPreview'
import { Title } from '../components/Title'
import { AppContextProvider } from '../context/AppContext'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppContextProvider>
        <main className={styles.main}>
          <Title/>
          <Input/>
          <LinkPreview/>
        </main>
      </AppContextProvider>
    </div>
  )
}

export default Home
